// This is automatically generated code -- do not edit!
// Generated from  
#include <vector>
namespace skeletons
{


  const char * AuthStrings_xml1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
  "<messages xmlns:if=\"Wt.WTemplate.conditions\">\r\n"
  "\r\n"
  "  <!-- BaseAuth, PasswordAuth and OAuth models -->\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.error-invalid-token\">The operation could not be completed: invalid token.</message>\r\n"
  "  <message id=\"Wt.Auth.error-token-expired\">The operation could not be completed: the token has expired.</message>\r\n"
  "  <message id=\"Wt.Auth.mail-sent\">An email has been sent. Follow the instructions to set a new password.</message>\r\n"
  "  <message id=\"Wt.Auth.info-email-confirmed\">Your email address is now confirmed.</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-error\">\r\n"
  "    Check failed\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-same\">\r\n"
  "    The same as the old one\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-similar\">\r\n"
  "    Based on the old one\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-short\">\r\n"
  "    Too short\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-long\">\r\n"
  "    Too long\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-simpleshort\">\r\n"
  "    Not enough different characters or classes for this length\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-simple\">\r\n"
  "    Not enough different characters or classes\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-personal\">\r\n"
  "    Based on personal information\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-word\">\r\n"
  "    Based on a dictionary word and not a passphrase\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-seq\">\r\n"
  "    Based on a common sequence of characters\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.passwdqc.reason-ok\">\r\n"
  "    Valid\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.GoogleService.badresponse\">\r\n"
  "    <p>Sorry, could not login using your Google account.</p>\r\n"
  "    <small>\r\n"
  "      <p>Google's identification server generated an unexpected\r\n"
  "	response.</p>\r\n"
  "    </small>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.FacebookService.badresponse\">\r\n"
  "    <p>Sorry, could not login using your Facebook account.</p>\r\n"
  "    <small>\r\n"
  "      <p>Facebook's identification server generated an unexpected\r\n"
  "	response.</p>\r\n"
  "    </small>\r\n"
  "  </message>\r\n"
  "  \r\n"
  "  <!-- LoginWidget -->\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.login-form-title\">Login</message>\r\n"
  "  <message id=\"Wt.Auth.login-form-info\"></message>\r\n"
  "  <message id=\"Wt.Auth.user-name\">User name</message>\r\n"
  "  <message id=\"Wt.Auth.user-name-info\">Enter your user name</message>\r\n"
  "  <message id=\"Wt.Auth.user-name-invalid\">Invalid</message>\r\n"
  "  <message id=\"Wt.Auth.email\">Email address</message>\r\n"
  "  <message id=\"Wt.Auth.email-info\">Enter your email address</message>\r\n"
  "  <message id=\"Wt.Auth.optional-email-info\">\r\n"
  "    Enter your email address (optional)\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.password\">Password</message>\r\n"
  "  <message id=\"Wt.Auth.password-info\">Enter your password</message>\r\n"
  "  <message id=\"Wt.Auth.remember-me\">Remember me</message>\r\n"
  "  <message id=\"Wt.Auth.remember-me-info.days\">\r\n"
  "    Keeps login for {1} days\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.remember-me-info.weeks\">\r\n"
  "    Keeps login for {1} weeks\r\n"
  "  </message>\r\n"
  "  <message id=\"Wt.Auth.lost-password\">Lost password</message>\r\n"
  "  <message id=\"Wt.Auth.login\">Login</message>\r\n"
  "  <message id=\"Wt.Auth.logout\">Logout</message>\r\n"
  "  <message id=\"Wt.Auth.throttle-retry\">Retry in {1}s</message>\r\n"
  "\r\n"
  "  <!-- RegistrationWidget -->\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.registration-form-title\">Registration</message>\r\n"
  "  <message id=\"Wt.Auth.registration-form-info\">Please complete the following information to register.</message>\r\n"
  "  <message id=\"Wt.Auth.password-registration\">Register using a user name and password:</message>\r\n"
  "  <message id=\"Wt.Auth.oauth-registration\">Register with an identity provider:</message>\r\n"
  "  <message id=\"Wt.Auth.or-oauth-registration\">Or, register with an identity provider:</message>\r\n"
  "  <message id=\"Wt.Auth.valid\">Valid</message>\r\n"
  "  <message id=\"Wt.Auth.choose-password\">Choose Password</message>\r\n"
  "  <message id=\"Wt.Auth.choose-password-info\">Choose a password</message>\r\n"
  "  <message id=\"Wt.Auth.repeat-password\">Repeat password</message>\r\n"
  "  <message id=\"Wt.Auth.repeat-password-info\">Re-enter your password</message>\r\n"
  "  <message id=\"Wt.Auth.email-invalid\">Invalid email address</message>\r\n"
  "  <message id=\"Wt.Auth.email-exists\">Email already registered</message>\r\n"
  "  <message id=\"Wt.Auth.oauth\">Your external account</message>\r\n"
  "  <message id=\"Wt.Auth.oauth-info\">Choose one of your accounts</message>\r\n"
  "  <message id=\"Wt.Auth.user-name-exists\">User already exists</message>\r\n"
  "  <message id=\"Wt.Auth.confirm-is-you\">User exists, is this you?</message>\r\n"
  "  <message id=\"Wt.Auth.user-name-tooshort\">Min. size {1} characters</message>\r\n"
  "  <message id=\"Wt.Auth.password-tooshort\">Min. size {1} characters</message>\r\n"
  "  <message id=\"Wt.Auth.passwords-dont-match\">Passwords don't match</message>\r\n"
  "  <message id=\"Wt.Auth.registration\">Registration</message>\r\n"
  "  <message id=\"Wt.Auth.register\">Register</message>\r\n"
  "  <message id=\"Wt.Auth.error-user-invalid\">Registration failed.</message>\r\n"
  "  <message id=\"Wt.Auth.email-unverified\">Please confirm your email first.</message>\r\n"
  "  <message id=\"Wt.Auth.confirm-email-first\">\r\n"
  "    <h5>Welcome!</h5>\r\n"
  "\r\n"
  "    You will be able to login after confirming your email address using the\r\n"
  "    email we've just sent you.\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <!-- PasswordPromptDialog -->\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.enter-password\">Enter your password</message>\r\n"
  "  <message id=\"Wt.Auth.password-prompt-form-title\">Enter your password</message>\r\n"
  "  <message id=\"Wt.Auth.password-prompt-form-info\"></message>\r\n"
  "  <message id=\"Wt.Auth.password-invalid\">Invalid password</message>\r\n"
  "\r\n"
  "  <!-- UpdatePasswordWidget -->\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.updatepassword\">Update password</message>\r\n"
  "  <message id=\"Wt.Auth.update-password-form-title\">Update password</message>\r\n"
  "  <message id=\"Wt.Auth.update-password-form-info\">Enter a new password below</message>\r\n"
  "\r\n"
  "  <!-- LostPasswordDialog -->\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.lostpassword\">Password forgotten? No sweat!</message>\r\n"
  "  <message id=\"Wt.Auth.lost-password-form-title\">Recover your password</message>\r\n"
  "  <message id=\"Wt.Auth.lost-password-form-info\">Please enter below the\r\n"
  "  email address which you used during registration. A mail will be\r\n"
  "  sent with instructions to enter a new password.</message>\r\n"
  "  <message id=\"Wt.Auth.send\">Send</message>\r\n"
  "\r\n"
  "  <!-- Message boxes -->\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.error\">Error</message>\r\n"
  "  <message id=\"Wt.Auth.notice\">Notice</message>\r\n"
  "\r\n"
  "  <!-- Emails -->\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.confirmmail.subject\">User account activation Link</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.confirmmail.body\">\r\n"
  "Hello {1},\r\n"
  "\r\n"
  "Thank you for joining!\r\n"
  "\r\n"
  "To complete your registration, please finally confirm your account by\r\n"
  "clicking on the following link or copying the URL into your browser.\r\n"
  " \r\n"
  "Please click here to confirm your registration or copy and paste the\r\n"
  "following URL into your browser: (Note: be sure to copy the entire\r\n"
  "URL, including any part of it which goes onto a second line.)\r\n"
  "\r\n"
  "{3}\r\n"
  "\r\n"
  "This text is resolved from the \"Wt.Auth.confirmmail.subject\",\r\n"
  "\"Wt.Auth.confirmmail.body\", and \"Wt.Auth.confirmmail.htmlbody\"\r\n"
  "resource keys.\r\n"
  "\r\n"
  "Good luck with your Wt application,\r\n"
  "\r\n"
  "The Wt team.\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.confirmmail.htmlbody\">\r\n"
  "    <h3>Hello {1},</h3>\r\n"
  "\r\n"
  "    <p>Thank you for joining!</p>\r\n"
  "\r\n"
  "    <p>To complete your registration, please finally confirm your\r\n"
  "    account by clicking on the following link or copying the URL into\r\n"
  "    your browser.</p>\r\n"
  " \r\n"
  "    <p>Please <a href=\"{3}\">click here to confirm</a> your\r\n"
  "    registration or copy and paste the following URL into your\r\n"
  "    browser: <i>(Note: be sure to copy the entire URL, including any\r\n"
  "    part of it which goes onto a second line.)</i></p>\r\n"
  "    \r\n"
  "    <b>{3}</b>\r\n"
  "\r\n"
  "    <p>\r\n"
  "      <i>Note to developer:</i>\r\n"
  "    </p>\r\n"
  "    <p>\r\n"
  "      This text is resolved from the \"Wt.Auth.confirmmail.subject\",\r\n"
  "      \"Wt.Auth.confirmmail.body\", and \"Wt.Auth.confirmmail.htmlbody\"\r\n"
  "      resource keys.\r\n"
  "    </p>\r\n"
  "\r\n"
  "    <p>Good luck with your Wt application,</p>\r\n"
  "\r\n"
  "    <p>The Wt team.</p>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.lostpasswordmail.subject\">Lost password instructions</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.lostpasswordmail.body\">\r\n"
  "Hello {1},\r\n"
  "\r\n"
  "This mail has been sent to you, because someone (presumably you?)\r\n"
  "indicated that he wishes to choose a new password, because the current\r\n"
  "password escapes his mind.\r\n"
  "\r\n"
  "If you requested this, then choose a new password by clicking on the\r\n"
  "following link or copying the URL into your browser. If you didn't\r\n"
  "request this, you can safely ignore and discard this email.\r\n"
  " \r\n"
  "Please copy and paste the following URL into your browser: (Note: be\r\n"
  "sure to copy the entire URL, including any part of it which goes onto\r\n"
  "a second line.)\r\n"
  " \r\n"
  "{3} \r\n"
  "\r\n"
  "This text is resolved from the \"Wt.Auth.lostpasswordmail.subject\",\r\n"
  "\"Wt.Auth.lostpasswordmail.body\", and \"Wt.Auth.lostpasswordmail.htmlbody\"\r\n"
  "resource keys.\r\n"
  "\r\n"
  "Good luck with your Wt application,\r\n"
  "\r\n"
  "The Wt team.\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.lostpasswordmail.htmlbody\">\r\n"
  "    <h3>Hello {1},</h3>\r\n"
  "\r\n"
  "    <p>This mail has been sent to you, because someone (presumably\r\n"
  "    you?)  indicated that he wishes to choose a new password, because\r\n"
  "    the current password escapes his mind.</p>\r\n"
  "\r\n"
  "    <p>If you requested this, then choose a new password by clicking\r\n"
  "    on the following link or copying the URL into your browser. If you\r\n"
  "    didn't request this, you can safely ignore and discard this\r\n"
  "    email.</p>\r\n"
  " \r\n"
  "    <p>Please <a href=\"{3}\">click here to choose a new password</a> or\r\n"
  "    copy and paste the following URL into your browser: <i>(Note: be\r\n"
  "    sure to copy the entire URL, including any part of it which goes\r\n"
  "    onto a second line.)</i></p>\r\n"
  "    \r\n"
  "    <b>{3}</b>\r\n"
  "\r\n"
  "    <p>\r\n"
  "      <i>Note to developer:</i>\r\n"
  "    </p>\r\n"
  "    <p>\r\n"
  "      This text is resolved from the\r\n"
  "      \"Wt.Auth.lostpasswordmail.subject\",\r\n"
  "      \"Wt.Auth.lostpasswordmail.body\", and\r\n"
  "      \"Wt.Auth.lostpasswordmail.htmlbody\" resource keys.\r\n"
  "    </p>\r\n"
  "\r\n"
  "    <p>Good luck with your Wt application,</p>\r\n"
  "\r\n"
  "    <p>The Wt team.</p>\r\n"
  "  </message>\r\n"
  "\r\n"
  "</messages>\r\n"
  "";
  std::vector<const char *> AuthStrings_xml()
  {
    std::vector<const char *> retval;

    retval.push_back(AuthStrings_xml1);

    return retval;
  }
}