// This is automatically generated code -- do not edit!
// Generated from  
#include <vector>
namespace skeletons
{


  const char * BootstrapTheme_xml1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
  "<messages xmlns:if=\"Wt.WTemplate.conditions\">\r\n"
  "  <message id=\"Wt.Auth.field\">\r\n"
  "    <![CDATA[\r\n"
  "    ${<if:{1}>}\r\n"
  "    <div class=\"control-group\">\r\n"
  "      <label for=\"${id:{1}}\" class=\"control-label\">\r\n"
  "        ${tr:Wt.Auth.{1}}\r\n"
  "      </label>\r\n"
  "      <div class=\"controls\">\r\n"
  "	${{1}} <span class=\"help-inline\">${{1}-info}</span>\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "    ${</if:{1}>}\r\n"
  "    ]]>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.template.login\">\r\n"
  "    <div class=\"span8 offset2 Wt-auth-login\">\r\n"
  "      <legend>${tr:Wt.Auth.login-form-title}</legend>\r\n"
  "      <p>${tr:Wt.Auth.login-form-info}</p>\r\n"
  "\r\n"
  "      <div class=\"form-horizontal\">\r\n"
  "	${<if:passwords>}\r\n"
  "          <div class=\"control-group\">\r\n"
  "	    <label for=\"${id:user-name}\" class=\"control-label\">\r\n"
  "	      ${user-name-label}\r\n"
  "	    </label>\r\n"
  "	    <div class=\"controls\">\r\n"
  "	      ${user-name} <span class=\"help-inline\">${user-name-info}</span>\r\n"
  "	    </div>\r\n"
  "	  </div>\r\n"
  "\r\n"
  "	  ${block:Wt.Auth.field password}\r\n"
  "	  ${block:Wt.Auth.field remember-me}\r\n"
  "	${</if:passwords>}\r\n"
  "\r\n"
  "	${<if:oauth>}\r\n"
  "	  <div class=\"control-group\">\r\n"
  "	    <div class=\"controls\">\r\n"
  "	      <p>Or login using:</p>\r\n"
  "	      ${icons}\r\n"
  "	    </div>\r\n"
  "	  </div>\r\n"
  "	${</if:oauth>}\r\n"
  "\r\n"
  "	<div class=\"form-actions\">\r\n"
  "	  <p>${login class=\"btn-primary\"}</p>\r\n"
  "	  <p>${lost-password class=\"btn-link\"} ${sep}\r\n"
  "	  ${register class=\"btn-link\"}</p>\r\n"
  "	</div>\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.template.registration\">\r\n"
  "    <div class=\"Wt-auth-registration\">\r\n"
  "      <p class=\"lead\">\r\n"
  "	${password-description}\r\n"
  "      </p>\r\n"
  "\r\n"
  "      <div class=\"form-horizontal\">\r\n"
  "        ${<if:user-name>}\r\n"
  "	  <div class=\"control-group\">\r\n"
  "	    <label for=\"${id:user-name}\" class=\"control-label\">\r\n"
  "	      ${user-name-label}\r\n"
  "	    </label>\r\n"
  "	    <div class=\"controls\">\r\n"
  "	      ${user-name}\r\n"
  "	      <span class=\"help-inline\">\r\n"
  "		${user-name-info} ${confirm-is-you class=\"btn-link\"}\r\n"
  "	      </span>\r\n"
  "	    </div>\r\n"
  "	  </div>\r\n"
  "	${</if:user-name>}\r\n"
  "\r\n"
  "	${block:Wt.Auth.field choose-password}\r\n"
  "	${block:Wt.Auth.field repeat-password}\r\n"
  "	${block:Wt.Auth.field email}\r\n"
  "\r\n"
  "	${<if:oauth>}\r\n"
  "	  <p class=\"lead\">\r\n"
  "	    ${oauth-description}\r\n"
  "	  </p>\r\n"
  "	  <div class=\"control-group\">\r\n"
  "	    <label class=\"control-label\">${tr:Wt.Auth.oauth}</label>\r\n"
  "	    <div class=\"controls\">\r\n"
  "	      ${icons}\r\n"
  "	    </div>\r\n"
  "	  </div>\r\n"
  "	${</if:oauth>}\r\n"
  "\r\n"
  "	<div class=\"modal-footer\"> <!-- assuming here we're in a dialog -->\r\n"
  "	  ${ok-button class=\"btn-primary\"} ${cancel-button}\r\n"
  "	</div>\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.template.update-password\">\r\n"
  "    <div class=\"Wt-auth-update-password\">\r\n"
  "      <div class=\"form-horizontal\">\r\n"
  "	<div class=\"control-group\">\r\n"
  "	  <label for=\"${id:user-name}\" class=\"control-label\">\r\n"
  "	    ${tr:Wt.Auth.user-name}\r\n"
  "	  </label>\r\n"
  "	  <div class=\"controls\">\r\n"
  "	    ${user-name}\r\n"
  "	  </div>\r\n"
  "	</div>\r\n"
  "\r\n"
  "	${block:Wt.Auth.field password}\r\n"
  "	${block:Wt.Auth.field choose-password}\r\n"
  "	${block:Wt.Auth.field repeat-password}\r\n"
  "\r\n"
  "	<div class=\"modal-footer\"> \r\n"
  "	  ${ok-button class=\"btn-primary\"} ${cancel-button}\r\n"
  "	</div>\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.template.lost-password\">\r\n"
  "    <div class=\"Wt-form Wt-auth-lost-password\">\r\n"
  "      <div class=\"form-horizontal\">\r\n"
  "	<div class=\"control-group\">\r\n"
  "	  <label for=\"${id:email}\" class=\"control-label\">\r\n"
  "	    ${tr:Wt.Auth.email}\r\n"
  "	  </label>\r\n"
  "	  <div class=\"controls\">\r\n"
  "	    ${email}\r\n"
  "	    <span class=\"help-inline\">\r\n"
  "	      <span>${tr:Wt.Auth.email-info}</span>\r\n"
  "	    </span>\r\n"
  "	  </div>\r\n"
  "	</div>\r\n"
  "\r\n"
  "	<div class=\"modal-footer\"> <!-- assuming here we're in a dialog -->\r\n"
  "	  ${send-button class=\"btn-primary\"} ${cancel-button}\r\n"
  "	</div>\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.template.password-prompt\">\r\n"
  "    <div class=\"Wt-form Wt-auth-password-prompt\">\r\n"
  "      <div class=\"form-horizontal\">\r\n"
  "	<div class=\"control-group\">\r\n"
  "	  <label for=\"${id:user-name}\" class=\"control-label\">\r\n"
  "	    ${tr:Wt.Auth.user-name}\r\n"
  "	  </label>\r\n"
  "	  <div class=\"controls\">\r\n"
  "	    ${user-name}\r\n"
  "	  </div>\r\n"
  "	</div>\r\n"
  "\r\n"
  "	${block:Wt.Auth.field password}\r\n"
  "      </div>\r\n"
  "\r\n"
  "      <div class=\"Wt-buttons\">\r\n"
  "	${ok-button} ${cancel-button}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.Auth.template.logged-in\">\r\n"
  "    <div class=\"Wt-auth-logged-in\">\r\n"
  "      <b>${user-name}</b> ${logout}\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "</messages>\r\n"
  "";
  std::vector<const char *> BootstrapTheme_xml()
  {
    std::vector<const char *> retval;

    retval.push_back(BootstrapTheme_xml1);

    return retval;
  }
}