// This is automatically generated code -- do not edit!
// Generated from  
#include <vector>
namespace skeletons
{


  const char * Wt_xml1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
  "<messages>\r\n"
  "  <message id=\"Wt.QuittedMessage\">\r\n"
  "    The application has stopped running, would you like to restart?\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WAbstractItemView.PageIOfN\"><b>{1}</b> of <b>{2}</b></message>\r\n"
  "  <message id=\"Wt.WAbstractItemView.PageBar.First\">&#x00ab; First</message>\r\n"
  "  <message id=\"Wt.WAbstractItemView.PageBar.Previous\">&#x2039; Previous</message>\r\n"
  "  <message id=\"Wt.WAbstractItemView.PageBar.Next\">Next &#x203a;</message>\r\n"
  "  <message id=\"Wt.WAbstractItemView.PageBar.Last\">Last &#x00bb;</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WCalendar.PrevMonth\">&#x00ab;</message>\r\n"
  "  <message id=\"Wt.WCalendar.NextMonth\">&#x00bb;</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WDate.Monday\">Monday</message>\r\n"
  "  <message id=\"Wt.WDate.Tuesday\">Tuesday</message>\r\n"
  "  <message id=\"Wt.WDate.Wednesday\">Wednesday</message>\r\n"
  "  <message id=\"Wt.WDate.Thursday\">Thursday</message>\r\n"
  "  <message id=\"Wt.WDate.Friday\">Friday</message>\r\n"
  "  <message id=\"Wt.WDate.Saturday\">Saturday</message>\r\n"
  "  <message id=\"Wt.WDate.Sunday\">Sunday</message>\r\n"
  "  <message id=\"Wt.WDate.3.Mon\">Mon</message>\r\n"
  "  <message id=\"Wt.WDate.3.Tue\">Tue</message>\r\n"
  "  <message id=\"Wt.WDate.3.Wed\">Wed</message>\r\n"
  "  <message id=\"Wt.WDate.3.Thu\">Thu</message>\r\n"
  "  <message id=\"Wt.WDate.3.Fri\">Fri</message>\r\n"
  "  <message id=\"Wt.WDate.3.Sat\">Sat</message>\r\n"
  "  <message id=\"Wt.WDate.3.Sun\">Sun</message>\r\n"
  "  <message id=\"Wt.WDate.January\">January</message>\r\n"
  "  <message id=\"Wt.WDate.February\">February</message>\r\n"
  "  <message id=\"Wt.WDate.March\">March</message>\r\n"
  "  <message id=\"Wt.WDate.April\">April</message>\r\n"
  "  <message id=\"Wt.WDate.May\">May</message>\r\n"
  "  <message id=\"Wt.WDate.June\">June</message>\r\n"
  "  <message id=\"Wt.WDate.July\">July</message>\r\n"
  "  <message id=\"Wt.WDate.August\">August</message>\r\n"
  "  <message id=\"Wt.WDate.September\">September</message>\r\n"
  "  <message id=\"Wt.WDate.October\">October</message>\r\n"
  "  <message id=\"Wt.WDate.November\">November</message>\r\n"
  "  <message id=\"Wt.WDate.December\">December</message>\r\n"
  "  <message id=\"Wt.WDate.3.Jan\">Jan</message>\r\n"
  "  <message id=\"Wt.WDate.3.Feb\">Feb</message>\r\n"
  "  <message id=\"Wt.WDate.3.Mar\">Mar</message>\r\n"
  "  <message id=\"Wt.WDate.3.Apr\">Apr</message>\r\n"
  "  <message id=\"Wt.WDate.3.May\">May</message>\r\n"
  "  <message id=\"Wt.WDate.3.Jun\">Jun</message>\r\n"
  "  <message id=\"Wt.WDate.3.Jul\">Jul</message>\r\n"
  "  <message id=\"Wt.WDate.3.Aug\">Aug</message>\r\n"
  "  <message id=\"Wt.WDate.3.Sep\">Sep</message>\r\n"
  "  <message id=\"Wt.WDate.3.Oct\">Oct</message>\r\n"
  "  <message id=\"Wt.WDate.3.Nov\">Nov</message>\r\n"
  "  <message id=\"Wt.WDate.3.Dec\">Dec</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WDatePicker.Close\">Close</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WDateTime.LessThanASecond\">less than a second</message>\r\n"
  "  <message id=\"Wt.WDateTime.second\">one second</message>\r\n"
  "  <message id=\"Wt.WDateTime.seconds\">{1} seconds</message>\r\n"
  "  <message id=\"Wt.WDateTime.minute\">one minute</message>\r\n"
  "  <message id=\"Wt.WDateTime.minutes\">{1} minutes</message>\r\n"
  "  <message id=\"Wt.WDateTime.hour\">one hour</message>\r\n"
  "  <message id=\"Wt.WDateTime.hours\">{1} hours</message>\r\n"
  "  <message id=\"Wt.WDateTime.day\">one day</message>\r\n"
  "  <message id=\"Wt.WDateTime.days\">{1} days</message>\r\n"
  "  <message id=\"Wt.WDateTime.week\">one week</message>\r\n"
  "  <message id=\"Wt.WDateTime.weeks\">{1} weeks</message>\r\n"
  "  <message id=\"Wt.WDateTime.month\">one month</message>\r\n"
  "  <message id=\"Wt.WDateTime.months\">{1} months</message>\r\n"
  "  <message id=\"Wt.WDateTime.year\">one year</message>\r\n"
  "  <message id=\"Wt.WDateTime.years\">{1} years</message>\r\n"
  "  <message id=\"Wt.WDateTime.null\"></message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WDateValidator.DateTooEarly\">The date must be after {1}</message>\r\n"
  "  <message id=\"Wt.WDateValidator.DateTooLate\">The date must be before {1}</message>\r\n"
  "  <message id=\"Wt.WDateValidator.WrongDateRange\">The date must be between {1} and {2}</message>\r\n"
  "  <message id=\"Wt.WDateValidator.WrongFormat\">Must be a date in the format '{1}'</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WDefaultLoadingIndicator.Loading\">Loading...</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WDialog.template\">\r\n"
  "    ${center-script}\r\n"
  "    ${layout}\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <!-- From WDialog-center.js: -->\r\n"
  "  <message id=\"Wt.WDialog.CenterJS\">\r\n"
  "    /* <![CDATA[ */\r\n"
  "(function(d,e,f){function g(){var a,b;if(typeof window.innerWidth===\"number\"){a=window.innerWidth;b=window.innerHeight}else{a=document.documentElement.clientWidth;b=document.documentElement.clientHeight}return{x:a,y:b}}function c(){var a=document.getElementById(d);if(a.style.display!=\"none\"&&a.style.visibility!=\"hidden\"){var b=g(),h=a.offsetWidth,i=a.offsetHeight;if(e){a.style.left=Math.round((b.x-h)/2)+\"px\";a.style.marginLeft=\"0px\"}if(f){a.style.top=Math.round((b.y-i)/2)+\"px\";a.style.marginTop=\"0px\"}a.style.visibility=\r\n"
  "\"visible\"}}window.addEventListener?window.addEventListener(\"DOMContentLoaded\",c,false):document.attachEvent(\"onDOMContentLoaded\",c)})($el,$centerX,$centerY);\r\n"
  "  /* ]]> */\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WDoubleValidator.NotANumber\">Must be a number</message>\r\n"
  "  <message id=\"Wt.WDoubleValidator.TooSmall\">The number must be larger than {1}</message>\r\n"
  "  <message id=\"Wt.WDoubleValidator.BadRange\">The number must be in the range {1} to {2}</message>\r\n"
  "  <message id=\"Wt.WDoubleValidator.TooLarge\">The number must be smaller than {1}</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WInPlaceEdit.Save\">Save</message>\r\n"
  "  <message id=\"Wt.WInPlaceEdit.Cancel\">Cancel</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WIntValidator.NotAnInteger\">Must be an integer number</message>\r\n"
  "  <message id=\"Wt.WIntValidator.TooSmall\">The number must be larger than {1}</message>\r\n"
  "  <message id=\"Wt.WIntValidator.BadRange\">The number must be in the range {1} to {2}</message>\r\n"
  "  <message id=\"Wt.WIntValidator.TooLarge\">The number must be smaller than {1}</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WLengthValidator.TooShort\">The input must be at least {1} characters</message>\r\n"
  "  <message id=\"Wt.WLengthValidator.BadRange\">The input must have a length between {1} and {2} characters</message>\r\n"
  "  <message id=\"Wt.WLengthValidator.TooLong\">The input must be no more than {1} characters</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WMediaPlayer.play\">Play</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.pause\">Pause</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.stop\">Stop</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.mute\">Mute</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.unmute\">Unmute</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.volume-max\">Maximum volume</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.repeat\">Repeat</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.repeat-off\">Repeat off</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.video-play-icon\">Play</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.full-screen\">Full screen</message>\r\n"
  "  <message id=\"Wt.WMediaPlayer.restore-screen\">Restore screen</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WMessageBox.Abort\">Abort</message>\r\n"
  "  <message id=\"Wt.WMessageBox.Cancel\">Cancel</message>\r\n"
  "  <message id=\"Wt.WMessageBox.Ignore\">Ignore</message>\r\n"
  "  <message id=\"Wt.WMessageBox.No\">No</message>\r\n"
  "  <message id=\"Wt.WMessageBox.NoToAll\">No to All</message>\r\n"
  "  <message id=\"Wt.WMessageBox.Ok\">Ok</message>\r\n"
  "  <message id=\"Wt.WMessageBox.Retry\">Retry</message>\r\n"
  "  <message id=\"Wt.WMessageBox.Yes\">Yes</message>\r\n"
  "  <message id=\"Wt.WMessageBox.YesToAll\">Yes to All</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WOverlayLoadingIndicator.Loading\">Loading...</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WRegExpValidator.Invalid\">Invalid input</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WValidator.Invalid\">This field cannot be empty</message>\r\n"
  "\r\n"
  "  <message id=\"Wt.true\">true</message>\r\n"
  "  <message id=\"Wt.false\">false</message>\r\n"
  "\r\n"
  "  <!-- templates -->\r\n"
  "\r\n"
  "  <message id=\"Wt.WMediaPlayer.template\">\r\n"
  "    <div class=\"jp-type-single\">\r\n"
  "      <div class=\"jp-jplayer\"> </div>\r\n"
  "      ${gui}\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WMediaPlayer.defaultgui-video\">\r\n"
  "    <div class=\"jp-video-play\">\r\n"
  "      ${video-play-btn}\r\n"
  "    </div>\r\n"
  "    <div class=\"jp-interface\">\r\n"
  "      <div class=\"jp-progress\">\r\n"
  "	${progress-bar}\r\n"
  "      </div>\r\n"
  "      ${current-time}\r\n"
  "      ${duration}\r\n"
  "      <div class=\"jp-controls-holder\">\r\n"
  "	<ul class=\"jp-controls\">\r\n"
  "	  <li>${play-btn}</li>\r\n"
  "	  <li>${pause-btn}</li>\r\n"
  "	  <li>${stop-btn}</li>\r\n"
  "	  <li>${mute-btn}</li>\r\n"
  "	  <li>${unmute-btn}</li>\r\n"
  "	  <li>${volume-max-btn}</li>\r\n"
  "	</ul>\r\n"
  "	${volume-bar}\r\n"
  "	<ul class=\"jp-toggles\">\r\n"
  "	  <li>${full-screen-btn}</li>\r\n"
  "	  <li>${restore-screen-btn}</li>\r\n"
  "	  <li>${repeat-btn}</li>\r\n"
  "	  <li>${repeat-off-btn}</li>\r\n"
  "	</ul>\r\n"
  "      </div>\r\n"
  "      <div class=\"jp-title\" style=\"display: ${title-display}\">\r\n"
  "	<ul>\r\n"
  "	  <li>${title}</li>\r\n"
  "	</ul>\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WMediaPlayer.defaultgui-audio\">\r\n"
  "    <div class=\"jp-interface\">\r\n"
  "      <ul class=\"jp-controls\">\r\n"
  "	<li>${play-btn}</li>\r\n"
  "	<li>${pause-btn}</li>\r\n"
  "	<li>${stop-btn}</li>\r\n"
  "	<li>${mute-btn}</li>\r\n"
  "	<li>${unmute-btn}</li>\r\n"
  "	<li>${volume-max-btn}</li>\r\n"
  "      </ul>\r\n"
  "      <div class=\"jp-progress\">\r\n"
  "	${progress-bar}\r\n"
  "      </div>\r\n"
  "      ${volume-bar}\r\n"
  "      <div class=\"jp-time-holder\">\r\n"
  "	${current-time}\r\n"
  "	${duration}\r\n"
  "	<ul class=\"jp-toggles\">\r\n"
  "	  <li>${repeat-btn}</li>\r\n"
  "	  <li>${repeat-off-btn}</li>\r\n"
  "	</ul>\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "    <div class=\"jp-title\" style=\"display: ${title-display}\">\r\n"
  "      <ul>\r\n"
  "	<li>${title}</li>\r\n"
  "      </ul>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WNavigationBar.template\">\r\n"
  "    <div class=\"navbar-inner\">\r\n"
  "      <div class=\"container\">\r\n"
  "	${collapse-button}\r\n"
  "	${expand-button}\r\n"
  "	${title-link}\r\n"
  "	${contents}\r\n"
  "      </div>\r\n"
  "    </div>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WNavigationBar.expand-button\">\r\n"
  "    <span class=\"icon-bar\"></span>\r\n"
  "    <span class=\"icon-bar\"></span>\r\n"
  "    <span class=\"icon-bar\"></span>\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WTreeViewNode.template\">\r\n"
  "    <div class=\"Wt-item ${trunk-class} ${selected}\">\r\n"
  "      ${cols-row}${expand}${no-expand}${col0}\r\n"
  "    </div>\r\n"
  "    ${children}\r\n"
  "  </message>\r\n"
  "\r\n"
  "  <message id=\"Wt.WTreeNode.template\">\r\n"
  "    <div class=\"Wt-item ${trunk-class} ${selected}\">\r\n"
  "      ${cols-row}${expand}${label-area}\r\n"
  "    </div>\r\n"
  "    ${children}\r\n"
  "  </message>\r\n"
  "</messages>\r\n"
  "";
  std::vector<const char *> Wt_xml()
  {
    std::vector<const char *> retval;

    retval.push_back(Wt_xml1);

    return retval;
  }
}